import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./theme-config.css";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Container, Theme, ThemePanel } from "@radix-ui/themes";
import NavBar from "./NavBar";
import AuthProvider from "@/_components/AuthProvider";
import Footer from "./Footer";
import QueryClientProvider from "./QueryClientProvider";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} px-2 `}>
        <QueryClientProvider>
          <AuthProvider>
            <Theme appearance="light" accentColor="iris" radius="large">
              <NavBar />
              <main className="">{children}</main>
              <Footer />
            </Theme>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
